spring:
  application:
   name: BACKGROUND-VERIFICATION
  config:
    import: optional:configserver:http://localhost:8071

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveliness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "BACKGROUND-VERIFICATION"
    description: "BACKGROUND VERIFICATION Portal"
    version: "1.0"

