spring:
  application:
   name: service-registry
  config:
    import: optional:configserver:http://localhost:8071

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/






