spring:
#   profiles:
#     active: dev
   application:
      name:
        EMPLOYEE-SELF-SERVICE
   config:
     import: optional:configserver:http://localhost:8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveliness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
   name: "EMPLOYEE-SELF-SERVICE"
   description: "Employee Self Service Portal"
   version: "1.0"

