spring:
  application:
    name: "api-gateway"
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true



management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveliness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      enabled: true
  info:
    env:
      enabled: true



info:
  app:
    name: "API-GATEWAY"
    description: "API-GATEWAY for routing"
    version: "1.0"
