apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  lables:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      lables:
        app: configserver
    spec:
      containers:
      - name: configserver
        image: reponame/appname
        ports:
        - containerPort: 8071
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  selector:
    app: configserver
  type: LoadBalancer
  ports:
    - protocal: TCP
      port: 8071
      targetPort: 8071
