server:
  port: 8071

spring:
  application:
   name: config-server
  profiles:
#  active: native
   active: git
  cloud:
   config:
    server:
     native:
#      search-locations: classpath:/config
     git:
       uri: "github url"
       default-label: main
       timeout: 10
       clone-on-start: true
       force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveliness-state:
        enabled: true
  endpoint:
    health:
      probes:
        enabled: true



