server:
  port: 8071

spring:
  application:
   name: config-server
  profiles:
   active: native
  cloud:
   config:
    server:
     native:
      search-locations: classpath:/config
#     git:
#       uri: "github url"
#       default-label: "RepositoryName"
#       timeout: 10(Waiting time for the response from the server)
#       clone-on-start: true(If true, the repository will be cloned on startup)
#       force-pull: true(If true, the repository will be pulled on startup)

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveliness-state:
        enabled: true
  endpoint:
    health:
      probes:
        enabled: true



